name: skdh

on:
  pull_request:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # install the listed requirements
        pip install -r gh_actions_requirements.txt
        # install testing requirements
        pip install -r test_requirements.txt
        # if macOS install libomp
        # if [ "$RUNNER_OS" == "macOS" ]; then
        #   HOMEBREW_NO_AUTO_UPDATE=1 brew install libomp
        # fi
      shell: bash
    - name: Install skdh
      run: |
        # if macOS, make sure to set the environment variables so that it can find gfortran-9
        # if [ "$RUNNER_OS" == "macOS" ]; then
        #   export F90=gfortran-9
        # fi
        # install scikit-dh
        pip install .
      shell: bash
    - name: Test with pytest
      run: |
        pytest test/